import gspread
from oauth2client.service_account import ServiceAccountCredentials
import nlu

scope = ['https://spreadsheets.google.com/feeds']
creds = ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope)
client = gspread.authorize(creds)

sheet = client.open("Abuse Data (generated by Alex)").sheet1

length = sheet.row_count
all_entries = sheet.get_all_records() #list of rows, each row is a dictionary
#print(all_entries)#['General Description'])
#nlu.analyze(all_entries[0]['General Description'])
for i in range(1, 10):
    sheet.update_cell(length, 8, "I just wrote to a spreadsheet using Python!")



#Now need to update the sheet with the results from NLP
#first 5 cols contain the original input data, first row is table col names
#sheet.update_cell(row i think, col i think, )
