import gspread
from oauth2client.service_account import ServiceAccountCredentials
import nlu

scope = ['https://spreadsheets.google.com/feeds']
creds = ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope)
client = gspread.authorize(creds)
sheet_read = client.open("Abuse Data (generated by Alex)").sheet1
sheet_write = client.open("Processed Information").sheet1


#length = sheet_read.row_count
all_entries_vals = sheet_read.get_all_values()
i = 1
empty = False
last_col_index = len(all_entries_vals[0]) - 1
while i < 100 and not empty:
    print(all_entries_vals[i])
    row_to_add = all_entries_vals[i]
    #row_to_add.append(keywords)
    #row_to_add.append(keywords)
    #row_to_add.append(keywords)
    sheet_write.insert_row(row_to_add, i + 1)
    i += 1
    if len(all_entries_vals[i][0]) == 0:
        empty = True
